<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>实验1</title>
</head>
<!-- 229970428谢浪 -->

<body>
    <script>
        // 1. 编写代码调用如下函数，将函数调用的代码和结果记录在实验报告中。 
        // function getSum(num1, num2) {
        //     var sum = num1 + num2;
        //     console.log(num1 + "+" + num2 + "=" + (num1 + num2))
        // }
        // getSum(2, 3)
        // 2. 运行如下代码，如果运行正确则记录运行结果；如果报错，则修改代码，记录下错误原因。
        // var getProduct = function (num1, num2) {
        //     console.log(num1 + "*" + num2 + "=" + num1 * num2)
        // }
        // getProduct(2, 4)
        // 3. 先阅读如下代码，思考输出的结果是什么？运行并记录输出结果。
        // var a = 100;
        // function test() {
        //     console.log(a);
        //     a = 10;
        //     console.log(a);
        // }
        // test()
        // console.log(a)
        // 4. 先阅读如下代码，思考输出的结果是什么？运行并记录输出结果。
        // var a = 10;
        // fun1();
        // function fun1() {
        //     var b = 20;
        //     console.log(a);
        //     console.log(b);
        //     var a = 30;
        // }
        // // 5. 运行如下代码，看看是否报错。
        // function fun2() {
        //     console.log(arguments[0])
        //     console.log(arguments[1])
        //     console.log(arguments[2])
        // }
        // fun2(1, 2, 3)
        // // 6. 尝试用for … in 的循环语句打印输出第5步中fun2调用时的参数，将记录实验代码。
        // function fun2(a, b) {
        //     for (let i in arguments) {
        //         console.log(arguments[i]);
        //     }
        // }
        // fun2(1, 2, 3);
        // // 7. 运行如下代码，并记录输出结果和原因。
        // "use strict";
        // num = 100;
        // // 8. 自行编写一段严格模式下报错的代码，记录代码并说明报错原因。
        // "use strict";
        // function test() {
        //     var x = 10;
        //     if (x > 5) {
        //         y = 20; // 未声明变量 y
        //     }
        //     console.log(y);
        // }
        // test();
        // 9. 为第8步中的错误代码添加try…catch语句块，友好显示错误信息。
        "use strict";
        //谢浪229970428
        function test() {
            var x = 10;
            try {
                if (x > 5) {
                    y = 20; // 未声明变量 y
                }
                console.log(y);
            } catch (e) {
                console.error("发生错误：", e.message);
            }
        }
        test();
    </script>
</body>

</html>